# Generated by Django 3.2.16 on 2026-06-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20260626_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='yandex_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
